# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2015.1
# Copyright (C) 2015 Xilinx Inc. All rights reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XExample" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_MYAXIL_BASEADDR" \
        "C_S_AXI_MYAXIL_HIGHADDR"

    xdefine_config_file $drv_handle "xexample_g.c" "XExample" \
        "DEVICE_ID" \
        "C_S_AXI_MYAXIL_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XExample" \
        "DEVICE_ID" \
        "C_S_AXI_MYAXIL_BASEADDR" \
        "C_S_AXI_MYAXIL_HIGHADDR"
}

