// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// MYAXIL
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : reserved
// 0x14 : Data signal of byte_wroffset
//        bit 31~0 - byte_wroffset[31:0] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of ctrl_reg
//        bit 31~0 - ctrl_reg[31:0] (Read/Write)
// 0x20 : Control signal of status_reg
//        bit 0  - status_reg_ap_vld (Read/COR)
//        others - reserved
// 0x24 : Data signal of status_reg
//        bit 31~0 - status_reg[31:0] (Read)
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XEXAMPLE_MYAXIL_ADDR_BYTE_WROFFSET_DATA 0x14
#define XEXAMPLE_MYAXIL_BITS_BYTE_WROFFSET_DATA 32
#define XEXAMPLE_MYAXIL_ADDR_CTRL_REG_DATA      0x1c
#define XEXAMPLE_MYAXIL_BITS_CTRL_REG_DATA      32
#define XEXAMPLE_MYAXIL_ADDR_STATUS_REG_CTRL    0x20
#define XEXAMPLE_MYAXIL_ADDR_STATUS_REG_DATA    0x24
#define XEXAMPLE_MYAXIL_BITS_STATUS_REG_DATA    32

