#pragma line 1 "example.cpp" ::: 0
#pragma line 1 "example.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 145 "/opt/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 403 "/opt/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 194
#pragma line 6 "<command line>" 2 ::: 197
#pragma line 1 "<built-in>" 2 ::: 198
#pragma line 1 "example.cpp" 2 ::: 199
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 200
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 228
#pragma line 128 "/usr/include/features.h" 3 4 ::: 329
#pragma line 149 "/usr/include/features.h" 3 4 ::: 343
#pragma line 177 "/usr/include/features.h" 3 4 ::: 345
#pragma line 193 "/usr/include/features.h" 3 4 ::: 348
#pragma line 350 "/usr/include/features.h" 3 4 ::: 379
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 383
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 418
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 424
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 447
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 488
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 494
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 512
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 518
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 522
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 524
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 528
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 538
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 591
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 632
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 653
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 677
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 678
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 680
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 682
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 683
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 708
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 719
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 724
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 725
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 726
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 733
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 769
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 772
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 774
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 802
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 804
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 806
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 867
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 874
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 892
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 897
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 908
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 977
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 991
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 994
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 995
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1027
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1043
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1068
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1071
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1076
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1098
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1119
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1122
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1133
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1143
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1145
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1149
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1198
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1199
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1205
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1207
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1231
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1242
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1283
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1285
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1307
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1367
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1382
#pragma line 526 "/usr/include/libio.h" 3 4 ::: 1394
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1396
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1402
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1453
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1469
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1486
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1518
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1595
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1734
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1754
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2007
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2018
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2055
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2087
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2155
#pragma line 943 "/usr/include/stdio.h" 3 4 ::: 2158
#pragma line 2 "example.cpp" 2 ::: 2160
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2161
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2194
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2219
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2222
#pragma line 96 "/usr/include/string.h" 3 4 ::: 2263
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2332
#pragma line 164 "/usr/include/string.h" 2 3 4 ::: 2375
#pragma line 199 "/usr/include/string.h" 3 4 ::: 2402
#pragma line 212 "/usr/include/string.h" 3 4 ::: 2404
#pragma line 236 "/usr/include/string.h" 3 4 ::: 2406
#pragma line 263 "/usr/include/string.h" 3 4 ::: 2411
#pragma line 315 "/usr/include/string.h" 3 4 ::: 2441
#pragma line 342 "/usr/include/string.h" 3 4 ::: 2446
#pragma line 436 "/usr/include/string.h" 3 4 ::: 2528
#pragma line 489 "/usr/include/string.h" 3 4 ::: 2559
#pragma line 517 "/usr/include/string.h" 3 4 ::: 2565
#pragma line 644 "/usr/include/string.h" 3 4 ::: 2654
#pragma line 3 "example.cpp" 2 ::: 2656
