#pragma line 1 "example.cpp" ::: -10
#pragma line 1 "example.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 145 "/opt/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 403 "/opt/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 184
#pragma line 6 "<command line>" 2 ::: 187
#pragma line 1 "<built-in>" 2 ::: 188
#pragma line 1 "example.cpp" 2 ::: 189
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 190
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 218
#pragma line 128 "/usr/include/features.h" 3 4 ::: 319
#pragma line 149 "/usr/include/features.h" 3 4 ::: 333
#pragma line 177 "/usr/include/features.h" 3 4 ::: 335
#pragma line 193 "/usr/include/features.h" 3 4 ::: 338
#pragma line 350 "/usr/include/features.h" 3 4 ::: 369
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 373
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 408
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 414
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 437
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 478
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 484
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 502
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 508
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 512
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 514
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 518
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 528
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 581
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 622
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 643
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 667
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 668
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 670
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 672
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 673
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 698
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 709
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 714
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 715
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 716
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 723
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 759
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 762
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 764
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 792
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 794
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 796
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 857
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 864
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 882
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 887
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 898
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 967
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 981
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 984
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 985
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1017
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1033
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1058
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1061
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1066
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1088
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1109
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1112
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1123
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1133
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1135
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1139
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1188
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1189
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1195
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1197
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1221
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1232
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1273
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1275
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1297
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1357
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1372
#pragma line 526 "/usr/include/libio.h" 3 4 ::: 1384
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1386
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1392
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1443
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1459
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1476
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1508
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1585
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1724
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1744
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1997
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2008
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2045
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2077
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2145
#pragma line 943 "/usr/include/stdio.h" 3 4 ::: 2148
#pragma line 2 "example.cpp" 2 ::: 2150
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2151
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2184
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2015.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2209
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 2212
#pragma line 96 "/usr/include/string.h" 3 4 ::: 2253
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2322
#pragma line 39 "/usr/include/xlocale.h" ::: 2364
#pragma line 164 "/usr/include/string.h" 2 3 4 ::: 2369
#pragma line 199 "/usr/include/string.h" 3 4 ::: 2396
#pragma line 212 "/usr/include/string.h" 3 4 ::: 2398
#pragma line 236 "/usr/include/string.h" 3 4 ::: 2400
#pragma line 263 "/usr/include/string.h" 3 4 ::: 2405
#pragma line 315 "/usr/include/string.h" 3 4 ::: 2435
#pragma line 342 "/usr/include/string.h" 3 4 ::: 2440
#pragma line 436 "/usr/include/string.h" 3 4 ::: 2522
#pragma line 489 "/usr/include/string.h" 3 4 ::: 2553
#pragma line 517 "/usr/include/string.h" 3 4 ::: 2559
#pragma line 644 "/usr/include/string.h" 3 4 ::: 2648
#pragma line 3 "example.cpp" 2 ::: 2650
#pragma line 30 "example.cpp" ::: 2680
