#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("a_req_din", 1, hls_out, 0, "ap_bus", "fifo_data", 1),
	Port_Property("a_req_full_n", 1, hls_in, 0, "ap_bus", "fifo_status", 1),
	Port_Property("a_req_write", 1, hls_out, 0, "ap_bus", "fifo_update", 1),
	Port_Property("a_rsp_empty_n", 1, hls_in, 0, "ap_bus", "fifo_status", 1),
	Port_Property("a_rsp_read", 1, hls_out, 0, "ap_bus", "fifo_update", 1),
	Port_Property("a_address", 32, hls_out, 0, "ap_bus", "unknown", 1),
	Port_Property("a_datain", 32, hls_in, 0, "ap_bus", "unknown", 1),
	Port_Property("a_dataout", 32, hls_out, 0, "ap_bus", "unknown", 1),
	Port_Property("a_size", 32, hls_out, 0, "ap_bus", "unknown", 1),
	Port_Property("stream_in_TDATA", 32, hls_in, 1, "axis", "in_data", 1),
	Port_Property("stream_in_TVALID", 1, hls_in, 1, "axis", "in_vld", 1),
	Port_Property("stream_in_TREADY", 1, hls_out, 1, "axis", "in_acc", 1),
	Port_Property("byte_wroffset", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("ctrl_reg", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("status_reg", 32, hls_out, 4, "ap_ovld", "out_data", 1),
	Port_Property("status_reg_ap_vld", 1, hls_out, 4, "ap_ovld", "out_vld", 1),
	Port_Property("interrupt_r", 1, hls_out, 5, "ap_ovld", "out_data", 1),
	Port_Property("interrupt_r_ap_vld", 1, hls_out, 5, "ap_ovld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "example";
